/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadDetailRouteImport } from './routes/lead-detail'
import { Route as LeadzzRouteImport } from './routes/leadzz'
import { Route as QuotesRouteImport } from './routes/quotes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadDetailRoute = LeadDetailRouteImport.update({
  id: '/lead-detail',
  path: '/lead-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadzzRoute = LeadzzRouteImport.update({
  id: '/leadzz',
  path: '/leadzz',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lead-detail': typeof LeadDetailRoute
  '/leadzz': typeof LeadzzRoute
  '/quotes': typeof QuotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lead-detail': typeof LeadDetailRoute
  '/leadzz': typeof LeadzzRoute
  '/quotes': typeof QuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lead-detail': typeof LeadDetailRoute
  '/leadzz': typeof LeadzzRoute
  '/quotes': typeof QuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lead-detail' | '/leadzz' | '/quotes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lead-detail' | '/leadzz' | '/quotes'
  id: '__root__' | '/' | '/lead-detail' | '/leadzz' | '/quotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadDetailRoute: typeof LeadDetailRoute
  LeadzzRoute: typeof LeadzzRoute
  QuotesRoute: typeof QuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-detail': {
      id: '/lead-detail'
      path: '/lead-detail'
      fullPath: '/lead-detail'
      preLoaderRoute: typeof LeadDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadzz': {
      id: '/leadzz'
      path: '/leadzz'
      fullPath: '/leadzz'
      preLoaderRoute: typeof LeadzzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadDetailRoute: LeadDetailRoute,
  LeadzzRoute: LeadzzRoute,
  QuotesRoute: QuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
